name: dcc-mer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.23
  - scipy>=1.10
  - scikit-learn>=1.2
  - pandas>=1.5
  - tqdm>=4.64
  - matplotlib>=3.7
  - seaborn>=0.12
  - pytorch=2.7.1
  - pytorch-cuda=12.6
  - pip:
      - transformers>=4.30

